version: '3.8'

services:
  lambda-app:
    build: .
    env_file:
      - /home/$USER/.env
    volumes:
      - ./html_runs:/var/task/html_runs
      - ./differences:/var/task/differences
      - ./master_summary:/var/task/master_summary
      - ./raw_diff:/var/task/raw_diff
      - ./master_summary_chinese:/var/task/master_summary_chinese
      - ./summarys:/var/task/summarys
      - ./summarys_chinese:/var/task/summarys_chinese
      - ./logs:/var/task/logs
    restart: always